# Generated by Django 3.2 on 2021-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210503_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deditcard',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='deditcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Available Balance'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Available Balance'),
        ),
    ]
